export const ON_INPUT_CHANGE = 'ON_INPUT_CHANGE';
export const ON_ADD_EXPENSE = 'ON_ADD_EXPENSE';
export const ON_SEARCH_FILTER_CHANGE = 'ON_SEARCH_FILTER_CHANGE';
export const ON_DELETE_EXPENSE = 'ON_DELETE_EXPENSE';
export const ON_SORT_CHANGE = 'ON_SORT_CHANGE';